before_script:
  - env
stages:
  - build
Build Container:
  stage: build
  tags:
    - k8s
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.7.0
    entrypoint: [""]
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --single-snapshot --destination containers.internal/$CI_PROJECT_NAME:latest
