ARG BASE=vue-storefront:test

FROM containers.internal/$BASE as build

RUN apk add --no-cache git curl build-base python2 && \
    npm install -g npm

RUN npm install -g lerna && \
    git clone https://github.com/danrcoull/vsf-payment-braintree.git /opt/vue-storefront/src/modules/payment-braintree

RUN lerna bootstrap

FROM node:15-alpine

COPY --from=0 /opt/vue-storefront /opt/vue-storefront

COPY entrypoint.sh /

WORKDIR /opt/vue-storefront

ENTRYPOINT "/entrypoint.sh"
